name: Unit Test CI

on:
  pull_request:
    branches: [main]

jobs:
  unittest:
    runs-on: self-hosted
    steps:
      - name: Debug no checkout
        run: |
          echo "runner alive, no checkout action used"
          whoami
          pwd
